apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1  # Adjust as needed for scaling
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: nlokeshbabu/backend:16387021923
        ports:
        - containerPort: 5000
        env:
          - name: DB-URL
            value: "mongodb"
          - name: MONGO_PORT
            value: "27017"
          - name:  MONGO-DB
            value: "clothing_ecom"
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo
                key: user-name
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo
                key: password

          - name: REDIS_HOST
            value: "redis-master.default.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password

        
        # Health Probes
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15  # Give time for Nginx to start
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30  # Ensure app is stable before liveness kicks in
          periodSeconds: 20

        # Resource Management
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "300m"


