apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3  # Adjust as needed for scaling
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: nlokeshbabu/backend:18428315413
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo
                key: user-name
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo
                key: password

          - name: REDIS_HOST
            value: "redis-master.redis.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password

        
        # Health Probes
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 15  # Give time for Nginx to start
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30  # Ensure app is stable before liveness kicks in
          periodSeconds: 20

        # Resource Management

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"