apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2  # Adjust as needed for scaling
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: nlokeshbabu/frontend:18744479679
        ports:
        - containerPort: 80
        env:
          - name: VITE_API_URL
            value: "http://backend-service:5000"
        
        command: ["/bin/sh", "-c"]
        args:
          - |
            sed -i "s|__API_URL__|${VITE_API_URL}|g" /usr/share/nginx/html/index.html;
            nginx -g 'daemon off;'

        # Health Probes
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15  # Give time for Nginx to start
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30  # Ensure app is stable before liveness kicks in
          periodSeconds: 20

        # Resource Management
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "300m"
