apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3  # Adjust as needed for scaling
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: nlokeshbabu/backend:{{ .Values.image.tag }}
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: user-name
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: password

          - name: REDIS_HOST
            value: "redis-master.default.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password

        # Health Probes
        readinessProbe:
            {{ toYaml .Values.readinessProbe | nindent 12 }}

        livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}

        # Resource Management
        resources:
            {{ toYaml .Values.resources | nindent 12 }}